### ISSUE TITLE
Add the "px" logo to the repo

### ISSUE THREAD

**Issue by paperdigits** [pixlsus/Presentations#1]
@patdavid Can you add the square logo with the "px" in the middle to the repo? I'd like to put it in the middle of some QR codes I plan to generate and place in my presentation.

**Comment by patdavid** [comment]
Absolutely! I'll upload all the image assets I have later today.

**Comment by patdavid** [comment]
I've added the PIXLS logos (both with and without the URL included).
The files are SVG files (as they are used in various places).
The background is the slategray as shown on the home page https://pixls.us. Feel free to adjust the background color as needed (white is common and seen on discuss).

**Comment by paperdigits** [comment]
Thanks!
